runtime: nodejs16

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 60m

handlers:
- url: /src
  static_dir: src

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto